### ISSUE TITLE
报错：'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'

### ISSUE THREAD

**Issue by lkqdmsk** [ftao/vpn-deploy-playbook#40]
按照wiki上面配置，第三步执行时报错，如下
[root@lkqdmsk vpn-deploy-playbook]# ansible-playbook  l2tp.yml  -l testvm
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 36, in <module>
    import ansible.playbook
  File "/usr/lib/python2.6/site-packages/ansible/playbook/__init__.py", line 20, in <module>
    import ansible.runner
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 62, in <module>
    from Crypto.Random import atfork
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    import FortunaGenerator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in <module>
    from Crypto.Util.number import ceil_shift, exact_log2, exact_div
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'

坏境：VPC，centos6.4

**Comment by ftao** [comment]
从未在  centos 测试过。 
你这感觉是 ansible 没有装好。 
请参考 下面， 重新安装 ansible 试试 
http://docs.ansible.com/intro_installation.html#latest-release-via-yum

**Comment by ftao** [comment]
close this issue due to inactive  & unsupported platform .
